### ISSUE TITLE
Conditions are not considered in admin panel.

### ISSUE THREAD

**Issue by basit74** [Maldicore/Admin#2]
I have defined a model like

```
class Product extends AppModel {
    public $adminSettings = array( 'icon' => 'product');
    public $belongsTo = array(
        'Category' => array(
            'className' => 'Category',
            'conditions' => array('Category.active' => 1),
            'order' => 'Category.name'
        )
    );
}
```

but unfortunatly the 'conditions' or 'order' is not  considered when creating a new Product.

**Comment by yusuf** [comment]
Would be able to help if you can give a little bit more info!
1. What is the expected behavior and what is the behavior you get?
2. Enable sql dump: in file Plugin/Admin/View/Layouts/default.php, uncomment line 98, refresh, what do you see?
