### ISSUE TITLE
Regarding setup of  Admin Panel

### ISSUE THREAD

**Issue by IKFTECH** [Maldicore/Admin#3]
My cake php version is - 2.2.4

I cant configure the Model - Fpllowing errors are shown - 

Undefined variable: navbar [ROOT\plugins\Admin\View\Admin\index.ctp, line 17]
Invalid argument supplied for foreach() [ROOT\plugins\Admin\View\Admin\index.ctp, line 17]

**Comment by yusuf** [comment]
We are finding it hard to replicate the error! Can you make sure you have the latest version from the repo and if you have the file app/Plugin/Admin/Controller/AdminAppController.php as the $navbar is defined in that file.

You do not need to modify any of the Plugin/Admin files, all settings should be done on your Model files at app/Model/\* as in the documentation https://github.com/Maldicore/Admin/blob/master/README.md

**Comment by pukhraj** [comment]
how to add manubar in admin plugin

**Comment by yusuf** [comment]
pukhraj The plugin will automatically add the menu based on the Models in your add/Model folder!

To setup your models refer the readme https://github.com/Maldicore/Admin/blob/master/README.md
