### ISSUE TITLE
Error: Call to a member function check() on a non-object

### ISSUE THREAD

**Issue by mattbilson** [Maldicore/Admin#8]
I've just installed the plugin and on accessing /admin, I get the following error :

Error: Call to a member function check() on a non-object
File: [[....]]/app/Plugin/Admin/Controller/AdminAppController.php
Line: 45

Does this plugin have any dependencies on other plugins? Or on any user management/authentication code being in place?

Thanks!

**Comment by sk-zk** [comment]
You need to add Session to your AppController:

class AppController extends Controller {
    public $components = array('DebugKit.Toolbar', 'Session');
}

**Comment by mattbilson** [comment]
Fixed.
Thanks!
